### ISSUE TITLE
Parsing Error: strconv.ParseFloat

### ISSUE THREAD

**Issue by joemulray** [simsalabim/stockprice#1]
Syntax related errors when using the CLI tool with stock price values over 1000.

<img width="408" alt="screen shot 2017-10-14 at 2 33 44 pm" src="https://user-images.githubusercontent.com/19763610/31576140-e924e972-b0ec-11e7-9213-92e1e1e1d7f4.png">

Great tool 👍

**Comment by simsalabim** [comment]
@joemulray thanks for the bug report! Fixed.
